monSite_Concession/monSite_Concessionnaire/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(length: 100)]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $pseudo = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function __construct()
    {
        $this->date_creation = new \DateTime();
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function getFormattedDateCreation(): string
    {
        return $this->date_creation->format('Y-m-d');
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }
}

monSite_Concession/monSite_Concessionnaire/src/Controller/UserController.php
<?php

namespace App\Controller;


use App\Form\RegistrationFormType;
use App\Form\UserUpdateFormType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

#[Route('/user')]
#[IsGranted('ROLE_USER')]
class UserController extends AbstractController
{
    #[Route('/', name: 'index_user')]
    public function index_user(UserRepository $userRepository ): Response
    {
        $users = $userRepository->findAll();
        return $this->render('user/index.html.twig', [
            'users' => $users,
        ]);
    }

    #[Route(path : "/update/{id}", name: "update_user")]
    public function update_user(int $id, UserRepository $userRepository, UserPasswordHasherInterface $userPasswordHasher, Request $request, EntityManagerInterface $em){

        $user = $userRepository->findOneBy([ "id" => $id ]); 
                    
        $form = $this->createForm(UserUpdateFormType::class , $user);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute("index_user");
        }
        return $this->render("user/update.html.twig", [
            'form' => $form->createView(),
        ]);
    }

    #[Route(path : "/delete/{id}", name: "delete_user")]
    public function delete_user(int $id, UserRepository $userRepository, EntityManagerInterface $em){
        $user = $userRepository->findOneBy(["id" => $id]);
        $em->remove($user);
        $em->flush();
        return $this->redirectToRoute("index_user");
    }
}

monSite_Concession/monSite_Concessionnaire/templates/user/index.html.twig
{% extends "bootstrap.html.twig" %}
{% block body %}
    <h1>Liste des utilisateurs</h1>
    <a href="{{ path("app_register") }}" class="btn btn-success my-3"> Ajouter un nouvel utilisateur</a>
    <div class="table-responsive">
        <table class="table table-striped align-middle">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Pseudo</th>
                    <th>Email</th>
                    <th>Date de création</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for key , value in users %}
                    <tr>
                        <td>{{ value.id }}</td>
                        <td>{{ value.pseudo }}</td>
                        <td>{{ value.email }}</td>
                        <td>{{ value.formattedDateCreation }}</td>
                        <td>
                                <a href="{{ path("update_user", { id : value.id }) }}" class="btn btn-warning">Modifier</a>
                            {% if value.id != app.user.id %}
                                <a href="{{ path("delete_user", { id : value.id }) }}" class="btn btn-danger ms-3">Supprimer</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

monSite_Concession/monSite_Concessionnaire/templates/user/update.html.twig
{% extends "bootstrap.html.twig" %}

{% block body %}

    <h1 class="py-3">Modifier l'utilisateur :</h1>

    {{ form_start(form) }}
        
        <div class="col-3 form-floating mb-3">
            {{ form_widget(form.email, { 'attr': {'class': 'form-control', 'placeholder': 'Email'|trans} }) }}
            {{ form_label(form.email, 'Email'|trans, { 'label_attr': {'class': 'form-label', 'for': 'floatingInput'} }) }}
            {% if form.email.vars.errors|length > 0 %}
                <div class="text-danger">
                    {{ form.email.vars.errors|first.message }}
                </div>
            {% endif %}
        </div>

        <div class="col-3 form-floating mb-3">
            {{ form_widget(form.plainPassword, { 'attr': {'class': 'form-control', 'placeholder': 'Mot de Passe'|trans} }) }}
            {{ form_label(form.plainPassword, 'Mot de Passe'|trans, { 'label_attr': {'class': 'form-label', 'for': 'floatingInput'} }) }}
            {% if form.plainPassword.vars.errors|length > 0 %}
                <div class="text-danger">
                    {{ form.plainPassword.vars.errors|first.message }}
                </div>
            {% endif %}
        </div>

        <div class="col-3 form-floating mb-3">
            {{ form_widget(form.pseudo, { 'attr': {'class': 'form-control', 'placeholder': 'Pseudo'|trans} }) }}
            {{ form_label(form.pseudo, 'Pseudo'|trans, { 'label_attr': {'class': 'form-label', 'for': 'floatingInput'} }) }}
            {% if form.pseudo.vars.errors|length > 0 %}
                <div class="text-danger">
                    {{ form.pseudo.vars.errors|first.message }}
                </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-outline-warning my-3">Modifier</button>
        
    {{ form_end(form) }}

{% endblock %}