monSite_Concession/monSite_Concessionnaire/src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    private ?string $modele = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?bool $en_vente = true;

    #[ORM\Column(length: 100)]
    private ?string $Prix = null;

    #[ORM\Column(length: 255)]
    private ?string $lien_redirection = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function getFormattedDateCreation(): string
    {
        return $this->date_creation->format('Y-m-d');
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function isEnVente(): ?bool
    {
        return $this->en_vente;
    }

    public function setEnVente(bool $en_vente): static
    {
        $this->en_vente = $en_vente;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): static
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getLienRedirection(): ?string
    {
        return $this->lien_redirection;
    }

    public function setLienRedirection(string $lien_redirection): static
    {
        $this->lien_redirection = $lien_redirection;

        return $this;
    }

}

monSite_Concession/monSite_Concessionnaire/src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\VehiculeRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function home( VehiculeRepository $vehiculeRepository ): Response
    {
        $vehicules = $vehiculeRepository->findAll();
        return $this->render('home/index.html.twig', [
            'vehicules' => $vehicules,
        ]);
    }

    #[Route('/legal', name: 'legal')]
    public function legal()
    {
        return $this->render('legal/index.html.twig');
    }
}

monSite_Concession/monSite_Concessionnaire/templates/home/index.html.twig
{% extends 'bootstrap.html.twig' %}

{% block body %}


<div class="container text-center">

  <h1 class="display-4 py-3">Bienvenue chez notre concessionnaire!</h1>

  <section class="carousel slide" id="diapo" data-bs-ride="carousel">
    <div class="carousel-indicators">
      {% for key, value in vehicules %}
        <button type="button" data-bs-target="#diapo" data-bs-slide-to="{{key}}" class=" {{ key is same as(0) ? "active" : "" }} " aria-current=" {{ key is same as(0) ? "true" : "" }} "></button>
      {% endfor %}
    </div>
            
    <div class="carousel-inner rounded">
      {% for key, value in vehicules %}
        <div class="carousel-item {{ key is same as(0) ? "active" : "" }} ">
            <img src="{{ value.image }}" alt=" Image {{ value.modele }} " class="d-block w-100" style="height:400px; object-fit:cover">
        </div>
      {% endfor %}                 
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#diapo" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#diapo" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
  </section>


  <h1 class="display-2 py-3">Disponibles à la vente:</h1>


  <div class="row justify-content-evenly">
    {% for key, value in vehicules %}
      {% if value.isEnVente %}            
        <div class="col-3">
          <div class="card mb-3">
            <h5 class="card-header"> {{ value.nom }} </h5>
            <img src=" {{ value.image }}" class="card-img-top" alt="Image {{ value.modele }}" style="height:150px; object-fit:cover">
            <div class="card-body d-flex flex-column align-items-center" style="min-height: 300px">
              <h5 class="card-title">{{ value.modele }}</h5>
              <p class="card-text">{{ value.description }}</p>
            </div>
            <div class="card-footer d-flex justify-content-between align-items-center">
              <p class="mb-0">Prix : {{ value.prix }}</p>
              <a href="javascript:void(0);" onclick="window.open('{{ value.lienredirection }}', '_blank');" class="btn btn-outline-dark">En savoir plus</a>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </div>
  <p class="fst-italic pt-3">Les images et informations présentés sur ce site appartiennent à leurs propriétaires respectifs</p>
</div>

{% endblock %}